name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install --no-root --no-cache

      - name: Install Black
        run: poetry add black@25.1.0 --dev

      - name: Run Black Code Formatter
        run: poetry run black --check --diff app weatherlib tests || (echo "Black formatting needed!" && exit 1)

      - name: Run Linting (weatherlib)
        run: poetry run pylint weatherlib --output-format=colorized

      - name: Run Linting (app)
        run: poetry run pylint app --output-format=colorized

      - name: Initialize Database
        run: poetry run python -c "from app.models import init_db; init_db()"

      - name: Run unit tests
        run: poetry run python -m unittest discover -v

      - name: Build documentation
        run: |
          poetry run mkdocs build  # Example: build docs into site/ directory

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && success()  # Only deploy on main branch if all prior steps succeeded
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # directory of built documentation
